# Generated by Django 6.0.5 on 2026-05-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='author',
            new_name='Rollno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='price',
            new_name='age',
        ),
    ]
