# Generated by Django 6.0.5 on 2026-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete_book', '0002_rename_author_student_rollno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Rollno',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Price',
        ),
    ]
